---
title: "Frederickson Lab Mission and Values"
author: "Megan Frederickson"
date: "16/09/2021"
output: github_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## CREATING A HEALTHY RESEARCH ENVIRONMENT

The Frederickson Lab studies mutualism. As such, we recognize and appreciate the value of reciprocally beneficial interactions, especially among individuals with distinct histories and ‘niches.’ As a lab, our primary goal is excellence in research, but we are guided by the belief that we do our best research when we work in a healthy and safe lab environment, when we recruit and support a diverse group of researchers, when we treat one another with respect and consideration, and when we achieve work-life balance. We expect all lab members to help establish and maintain a healthy, safe, diverse, inclusive, and considerate research environment. This mission statement provides more details about how we hope to work towards this goal. 

Please note that this is not a legal document, and does not replace or supersede departmental and universities policies. 

## PERSONAL & INTERPERSONAL CONDUCT

- How to treat one another
- Equity, diversity, & inclusion
- Sexual harassment, violence, etc.
- Lab communications & social media
-Power imbalances

All lab members are expected to treat others with respect and kindness. Putdowns, offensive jokes, physical or sexual violence or harassment of any kind are not acceptable, either in person or via digital/online communication. 

The Frederickson Lab is deeply committed to the fair and equitable treatment of all current and prospective lab members. Harrassment or other forms of discrimination based on gender, race, religion, sexual orientation, (dis)ability, immigration status, physical appearance, etc. will not be tolerated. Making everyone feel supported and included is necessary to develop a collaborative and productive lab. A diverse research group brings a greater breadth of lived experiences and skills, which helps promote diversity of thought within the group. This generates a research atmosphere more conducive to the kind of critical thinking and unbiased reasoning that is fundamental to doing good science. 

We expect respectful conduct to extend to your life off campus, because you represent the lab, the Department of Ecology & Evolutionary Biology, and the University of Toronto more broadly. That said, we also recognize and respect your individual agency in making choices about how to live your life. 